name: Publish-Docs

on:
  push:
    branches:
      - main

jobs:
  Update-yaml-build-publish-docs:
    name: step 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:  ${{secrets.GH_TOKEN}}
      - name: Install Dependencies
        run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - name: Update the yaml file
        run: python ${{ github.workspace }}/update_mkdocs.py
      - name: Build and Publish
        run: |
          git config --global user.email ${{vars.USER_MAIL}}
          git config --global user.name ${{vars.USER_NAME}}
          ${{ github.workspace }}/publish.sh
