name: StackExchange-Notifier workflow file

on:
  push:
    branches:
      - main

jobs:
  Update-yaml-build-publish-docs:
    name: step 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - name: Update the yaml file
        run: python ${{ github.workspace }}/update_mkdocs.py
      - name: Build and Publish
        run: ${{ github.workspace }}/publish.sh
